# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Pagewaiter
tagline:          'Frontend Develpment by Jason Mosley'
description:      'The Frontend Develpment Blog and Portfolio of Jason Mosley'
url:              http://pagewaiter.github.io
baseurl:          /

author:
  name:           'Jason Mosley'
  url:            https://twitter.com/mosley

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/Pagewaiter/pagewaiter.github.io
